import Foundation

struct Card:Identifiable {
    let id = UUID()
    let title: String
    let content: String
    let detail: String
    let bottomText: String
    let imageUrl: String
    var expand: Bool
   
    static func all() -> [Card]{
        return [
            Card(title: "Featured App", content: "Marco Polo",detail: "Born in Venice, Marco learned the mercantile trade from his father and his uncle, Niccolò and Maffeo, who travelled through Asia and met Kublai Khan. In 1269, they returned to Venice to meet Marco for the first time. The three of them embarked on an epic journey to Asia, exploring many places along the Silk Road until they reached Cathay (China). They were received by the royal court of Kublai Khan, who was impressed by Marco's intelligence and humility. Marco was appointed to serve as Khan's foreign emissary, and he was sent on many diplomatic missions throughout the empire and Southeast Asia, such as in present-day Burma, India, Indonesia, Sri Lanka and Vietnam.Marco was appointed to serve as Khan's foreign emissary, and he was sent on many diplomatic missions throughout the empire and Southeast Asia, such as in present-day Burma, India, Indonesia, Sri Lanka and Vietnam.", bottomText: "Play with Marco Polo and explore the whole world.", imageUrl: "p0",expand: false),
            Card(title: "Champion", content: "Cristiano Ronaldo",detail: "Born and raised in Madeira, Ronaldo began his senior club career playing for Sporting CP, before signing with Manchester United in 2003, aged 18. After winning the FA Cup in his first season, he helped United win three successive Premier League titles, the UEFA Champions League, and the FIFA Club World Cup; at age 23, he won his first Ballon d'Or. In 2009, Ronaldo was the subject of the then-most expensive association football transfer when signed for Real Madrid in a transfer worth €94 million (£80 million). There, Ronaldo won 15 trophies, including two La Liga titles, two Copas del Rey, and four UEFA Champions League titles, and became the club's all-time top goalscorer.Real Madrid in a transfer worth €94 million (£80 million). There, Ronaldo won 15 trophies, including two La Liga titles, two Copas del Rey, and four UEFA Champions League titles, and became the club's all-time top goalscorer. ", bottomText: "Play with Ronaldo and the other teams.", imageUrl: "p1",expand: false),
            Card(title: "Special Game For You", content: "Pubg",detail: "Battlegrounds was first released for Microsoft Windows via Steam's early access beta program in March 2017, with a full release in December 2017. The game was also released by Microsoft Studios for the Xbox One via its Xbox Game Preview program that same month, and officially released in September 2018. A free-to-play mobile version for Android and iOS was released in 2018, in addition to a port for the PlayStation 4. A version for the Stadia streaming platform was released in April 2020. Battlegrounds is one of the best-selling and most-played video games of all time. The game had sold over 70 million copies by 2020, with PUBG Mobile having been downloaded over 600 million times.PlayStation 4. A version for the Stadia streaming platform was released in April 2020. Battlegrounds is one of the best-selling and most-played video games of all time. The game had sold over 70 million copies by 2020, with PUBG Mobile having been downloaded over 600 million times.", bottomText: "Play with your team and kill everyone.", imageUrl: "p2",expand: false),
            Card(title: "Your Health is Important", content: "Health",detail: "Just as there was a shift from viewing disease as a state to thinking of it as a process, the same shift happened in definitions of health. Again, the WHO played a leading role when it fostered the development of the health promotion movement in the 1980s. This brought in a new conception of health, not as a state, but in dynamic terms of resiliency.Thus, health referred to the ability to maintain homeostasis and recover from insults. Mental, intellectual, emotional and social health referred to a person's ability to handle stress, to acquire skills, to maintain relationships, all of which form resources for resiliency and independent living.[4] This opens up many possibilities for health to be taught, strengthened and learned.Thus, health referred to the ability to maintain homeostasis and recover from insults. Mental, intellectual, emotional and social health referred to a person's ability to handle stress, to acquire skills, to maintain relationships, all of which form resources for resiliency and independent living.[4] This opens up many possibilities for health to be taught, strengthened and learned.", bottomText: "Take Care Of Yourself", imageUrl: "p3",expand: false)
        ]
    }
}
